import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#89ceff",
        "error-container": "#ffdad6",
        "surface-container-high": "#dce9ff",
        "primary-fixed": "#d8e2ff",
        "secondary-container": "#8fa7fe",
        "on-secondary-fixed-variant": "#264191",
        "on-tertiary": "#ffffff",
        "outline": "#727785",
        "on-secondary-fixed": "#00164e",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#adc6ff",
        "on-tertiary-container": "#fcfcff",
        "on-primary": "#ffffff",
        "primary": "#0058be",
        "on-primary-fixed": "#001a42",
        "surface-container-low": "#eff4ff",
        "primary-fixed-dim": "#adc6ff",
        "on-secondary-container": "#1d3989",
        "background": "#f8f9ff",
        "on-tertiary-fixed": "#001e2f",
        "error": "#ba1a1a",
        "tertiary": "#00628d",
        "surface-variant": "#d3e4fe",
        "on-error-container": "#93000a",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#005ac2",
        "secondary-fixed-dim": "#b6c4ff",
        "on-surface-variant": "#424754",
        "surface-bright": "#f8f9ff",
        "inverse-surface": "#213145",
        "on-error": "#ffffff",
        "secondary-fixed": "#dce1ff",
        "outline-variant": "#c2c6d6",
        "surface-container": "#e5eeff",
        "tertiary-container": "#007cb1",
        "on-primary-container": "#fefcff",
        "surface-dim": "#cbdbf5",
        "on-secondary": "#ffffff",
        "on-background": "#0b1c30",
        "tertiary-fixed": "#c9e6ff",
        "primary-container": "#2170e4",
        "secondary": "#4059aa",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-fixed-variant": "#004c6e",
        "surface": "#f8f9ff",
      },
      spacing: {
        "sidebar-width": "260px",
        "card-gap": "20px",
        "container-padding": "24px",
        "gutter": "16px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "1rem",
      },
      boxShadow: {
        "card": "0px 4px 12px rgba(30, 58, 138, 0.08)",
        "card-hover": "0px 12px 32px rgba(30, 58, 138, 0.15)",
        "modal": "0px 12px 32px rgba(30, 58, 138, 0.15)",
      },
      keyframes: {
        rise: {
          "0%": { transform: "translateY(0) rotate(0deg)", opacity: "0" },
          "10%": { opacity: "0.5" },
          "90%": { opacity: "0.5" },
          "100%": { transform: "translateY(-100vh) rotate(360deg)", opacity: "0" },
        },
        wave: {
          "0%": { transform: "translateX(0) translateZ(0) scaleY(1)" },
          "50%": { transform: "translateX(-25%) translateZ(0) scaleY(0.8)" },
          "100%": { transform: "translateX(-50%) translateZ(0) scaleY(1)" },
        },
        fadeIn: {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        rise: "rise 10s infinite ease-in",
        wave: "wave 20s linear infinite",
        fadeIn: "fadeIn 0.4s ease forwards",
      },
    },
  },
  plugins: [],
};

export default config;
